List<String> myIndex = [
'تقريظ أ. ياسر السمرى',
'تقريظ د. محمد فؤاد عبدالمجيد',
'تقريظ أ.د. عبدالقيوم السندى',
'مقدمة المؤلف-الإصدار الخامس',
'تعريف باللإمام ابن الجزرى',
  'مدخل لدراسة الدرة',
//'فصل فى الأوجه المقدمة في الأداء',
//'فصل فيما زادته الدرة على الشاطبية',
'مقدمة النظم',
'باب البسملة وأم القرآن-1',
  'باب البسملة وأم القرآن-2',
'الإدغام الكبير',
'هاء الكناية',
'المد والقصر',
'الهمزتان من كلمة',
// 'الاستفهام المكرر',
'الهمزتان من كلمتبن',
'الهمز المفرد 1',
'الهمز المفرد 2',
'النقل والسكت والوقف على الهمز',
 // 'النقل والسكت والوقف على الهمز-2',
'الإدغام الصفير ',

'النون الساكنة والتنوين',
'الفتح والإمالة',
'الراءات واللامات والوقف على المرسوم-1',//LGQYof0_fgk

'ياءات الإضافة',
'الياءات الزوائد',
  // 'الياءات الزوائد-2',
'باب فرش الحروف :فرش سورة البقرة-1',
  'سورة البقرة -2',
  'سورة البقرة -3',
  'سورة البقرة -4',
  'سورة البقرة -5',
  'سورة البقرة -6',
  'سورة البقرة -7',
  'سورة البقرة -8',
  'سورة البقرة -9',
  'سورة البقرة -10',
' سورة آل عمران-1',
  ' سورة آل عمران-2',
  ' سورة آل عمران-3',
  ' سورة آل عمران-4',
' سورة النساء-1',
  ' سورة النساء-2',
'فرش سورة المائدة',
'سورة الأنعام-1',
  'سورة الأنعام-2',
  'سورة الأنعام-3',
'سورة الأعراف والأنفال-1',
  'سورة الأعراف والأنفال-2',
  'سورة الأعراف والأنفال-3',
'سورة التوبة ويونس وهود عليهما السلام-1',
  'سورة التوبة ويونس وهود عليهما السلام-2',
  'سورة التوبة ويونس وهود عليهما السلام-3',
  'سورة التوبة ويونس وهود عليهما السلام-4',
'سورة يوسف-عليه السلام- والرعد',
' سورة إبراهيم-عليه السلام -والحجر والنحل',
'سورة الكهف',
'ومن سورة مريم-عليها السلام-إلى سورة الفرقان',
'ومن سورة الفرقان إلى سورة الروم',
'سورة الروم ولقمان -عليه السلام- والسجدة',
'سورة الأحزاب وسبأو فاطر',
'سورة يس-عليه السلام -والصافات',
'ومن سورة ص إلى سورة الأحقاف',
'ومن سورة الأحقاف إلى سورة الرحمن',
'ومن سورة الرحمن إلى سورة الإمتحان',
'ومن سورة الإمتحان إلى سورة الجن',
'ومن سورة الجن إلى سورة المرسلات',
'ومن سورة المرسلات إلى سورة الغاشية',
'ومن سورة الغاشية إلى آخر القرآن',
  'فصل فى الأوجه المقدمة فى الأداء',
  'فصل فيما زادته الدرة على الشاطبية',
'المراجع',
  'الفهرس'


];

List<int> pageNum = [
5,
  6,
  7,
  9,
  10,
  13,
  20,
  37,
  37,
  52,
  62,
  71,
  73,
  87,
  91,
  91,
  110,
  122,
  135,
  137,
  146,
  162,
  171,
  187,
  187,
  187,187,187,187,187,187,187,187,
  249,249,249,249,
  266,266,
  279,
  287,287,287,
  306,306,306,
  328,328,328,328,
  351,
  355,
  371,
  381,
  410,
  423,
  429,
  441,
  453,
  470,
  480,
  488,
  493,
  501,
  509,
  520,
  525,
  547,
  549
// 9,
// 10,
// 11,
// 13,
// 14,
// 24,
// 30,
// 58,
// 80,
// 100,
// 114,
// 126,
// 129,
// 141,
// 148,
// 154,
//   154,
// 179,
// 194,
//   194,
// 210,
// 212,
// 222,
//   222,
// 240,
// 253,
//   253,
// 275,
//   275,
//   275,
//   275,
//   275,
//   275,
//   275,
//   275,
//   275,
//   275,
//
// 356,
//   356,
//   356,
//   356,
// 378,
//   378,
// 395,
//   395,
//   395,
// 405,
//   405,
//   405,
// 430,
//   457,
//   457,
//   457,
//
// 457,
// 486,
// 491,
// 512,
// 524,
// 559,
// 576,
// 584,
// 599,
// 614,
// 635,
// 647,
// 657,
// 663,
// 673,
// 683,
// 697

];


List<String> myVideoList=[
'https://youtu.be/aOZYPsJLkU0',
'https://youtu.be/23vGLSeklqU',
'https://youtu.be/E2ZQDhBPNxA',
'https://youtu.be/7M9LBCWgB3g',
'https://youtu.be/xLQ2H_ibPfQ',
'https://youtu.be/RJGCzhAcAoE',
'https://youtu.be/SZxigsibed4',
'https://youtu.be/jmTsi0LT5k8',
'https://youtu.be/YZwn7niNGEk',
'https://youtu.be/fqVDeu-Qgo0',
//'https://youtu.be/cV0ZqZe7Vss',//الاستفهام المكرر
'https://youtu.be/RYq_kMo-Ues',
'https://youtu.be/135yzuL8J8o',
'https://youtu.be/Mrd3wbnkgeo',
'https://youtu.be/Kk5xy4AUqVY',

  'https://youtu.be/SZTFoAE9CS0?si=EoD0PqatZ_EuRcq6',//adgham sagheer

'https://youtu.be/lG7TmAVRbOU?si=R4_sJOzu9zYYb-fe',// noon sakna
  'https://www.youtube.com/watch?v=LGQYof0_fgk',//fath emala

//'https://youtu.be/SZTFoAE9CS0',
//'https://youtu.be/lG7TmAVRbOU',
'https://youtu.be/LGQYof0_fgk',//raaat lamat
  'https://youtu.be/ppbx6oMteeI',//yaat edafa
 'https://www.youtube.com/watch?v=itpb-TgIlOc',// yaa aat zawayed
//   'https://youtu.be/uri5-hVnOso?si=TEoT7oam8FAqYYx5',//edgham sagher
// 'https://youtu.be/-yNSUtXwU2U',
// 'https://youtu.be/eUTco5YXScU',//raat lamat
//
// 'https://youtu.be/itpb-TgIlOc',
// 'https://youtu.be/B_4-tdnDBk4',
'https://youtu.be/7625SAjDtjI',// bakara 1
'https://youtu.be/EBvdHa85-9A',
'https://youtu.be/_u-IrpTwj8k',
'https://youtu.be/1Bx3s3UN2Xs',
'https://youtu.be/XvpzZGR3UNU',
'https://youtu.be/E-sh_fm5KMo',
'https://youtu.be/rG6DxnqbZqw',
'https://youtu.be/OW5Iqxri8sI',
'https://youtu.be/BpmXXdxui9Q',
'https://youtu.be/IH-xtFNpOk8',
'https://youtu.be/lmRiOEfMoq4',
'https://youtu.be/F5MS6vlc8_0',
'https://youtu.be/WGjKOyJM-go',
'https://youtu.be/LdaCfWlL1cI',
'https://youtu.be/Lillkqwkr4g',
'https://youtu.be/KlcQhb_KXX8',
'https://youtu.be/_N_LBhCZ-t8',
'https://youtu.be/J3mGbFDubtc',
'https://youtu.be/aaTSquIBn9k',
'https://youtu.be/nN6Y1860UWw',
'https://youtu.be/4BFbhU2mV-w',
'https://youtu.be/p5DGl6EmGXk',
'https://youtu.be/aUJp_Lgwmbg',
'https://youtu.be/E4nRiOVCWbQ',
'https://youtu.be/f0hCQWidp4M',
'https://youtu.be/gbFBfsgbr4o',
'https://youtu.be/XlcrsEYx-tk',
'https://youtu.be/GzSOsMH1-Qw',
'https://youtu.be/3UHIrX_Evm8'
];